site_name: "validators"
site_description: "Automatic documentation from sources, for MkDocs."
site_url: "https://yozachar.github.io/pyvalidators/"
repo_url: "https://github.com/python-validators/validators/"
edit_uri: "edit/master/docs/"
repo_name: "validators/validators"
site_dir: "site"
watch: [README.md, src/validators/]

theme:
  name: material
  icon:
    logo: material/marker-check
  favicon: assets/icons/favicon.svg
  font:
    text: Inter
    code: "Fira Code"
  features:
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
          import:
            - https://docs.python-requests.org/en/master/objects.inv
  - git-revision-date-localized
  - mike

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/python-validators
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/validators
  version:
    provider: mike
    default: stable

copyright: Copyright &copy; 2013 - 2024 Konsta Vesterinen

nav:
  - Home: index.md
  - Install and Use: install_and_use.md
  - API:
      - api/between.md
      - api/crypto_addresses.md
      - api/card.md
      - api/country.md
      - api/cron.md
      - api/domain.md
      - api/email.md
      - api/encoding.md
      - api/finance.md
      - api/hashes.md
      - api/hostname.md
      - api/i18n.md
      - api/iban.md
      - api/ip_address.md
      - api/length.md
      - api/mac_address.md
      - api/slug.md
      - api/url.md
      - api/utils.md
      - api/uuid.md
